tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "hugo"
brew "mas"
brew "pv"
brew "rbenv"
brew "stow"
brew "tmux"
cask "docker"
cask "electrum"
cask "google-chrome"
cask "graphiql"
cask "iterm2"
cask "libreoffice"
cask "robo-3t"
cask "tor-browser"
cask "virtualbox"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Logic Pro X", id: 634148309
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 880001334
mas "Slack", id: 803453959
mas "WhatsApp", id: 1147396723
